{% set name = "shibuya" %}
{% set version = "2025.2.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/shibuya-{{ version }}.tar.gz
  sha256: 526d114164970923017502e617bf21e3e520f1933ce7a7c203479141760b1536

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - sphinx

test:
  imports:
    - shibuya
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://shibuya.lepture.com/
  summary: A clean, responsive, and customizable Sphinx documentation theme with light/dark mode.
  dev_url: https://github.com/lepture/shibuya
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daylinmorgan
