{% set name = "shibuya" %}
{% set version = "2025.11.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/shibuya-{{ version }}.tar.gz
  sha256: 7a8a2b4ac6c3fb8d2f75a15098458e376f5af33cfff45b21e5816e41dfcc5dd3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - sphinx
    - pygments-styles

test:
  imports:
    - shibuya
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://shibuya.lepture.com/
  summary: A clean, responsive, and customizable Sphinx documentation theme with light/dark mode.
  dev_url: https://github.com/lepture/shibuya
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daylinmorgan
