{% set name = "shibuya" %}
{% set version = "2024.12.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/shibuya-{{ version }}.tar.gz
  sha256: cde2f1d6b9b00321c9b47a782874e57cb0d4e3de399bf187c39d8edb84d6e73f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - sphinx

test:
  imports:
    - shibuya
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://shibuya.lepture.com/
  summary: A clean, responsive, and customizable Sphinx documentation theme with light/dark mode.
  dev_url: https://github.com/lepture/shibuya
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - daylinmorgan
